[tool.poetry]
name = "random-quote-generator"
version = "0.1.0"
description = ""
authors = ["Guilherme Costa <glhrmcosta91@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
